#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interfaces
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="eventos")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    partial void Insertevento(evento instance);
    partial void Updateevento(evento instance);
    partial void Deleteevento(evento instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["eventosConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<usuario> usuario
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
		
		public System.Data.Linq.Table<evento> evento
		{
			get
			{
				return this.GetTable<evento>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _rut;
		
		private string _usuario1;
		
		private string _pass;
		
		private string _nombres;
		
		private string _apellidos;
		
		private System.DateTime _fecha_nacimiento;
		
		private int _telefono;
		
		private string _correo;
		
		private char _sexo;
		
		private string _descripcion_perfil;
		
		private System.Nullable<int> _id_imagen;
		
		private EntitySet<evento> _evento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void OnrutChanging(string value);
    partial void OnrutChanged();
    partial void Onusuario1Changing(string value);
    partial void Onusuario1Changed();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void Onfecha_nacimientoChanging(System.DateTime value);
    partial void Onfecha_nacimientoChanged();
    partial void OntelefonoChanging(int value);
    partial void OntelefonoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnsexoChanging(char value);
    partial void OnsexoChanged();
    partial void Ondescripcion_perfilChanging(string value);
    partial void Ondescripcion_perfilChanged();
    partial void Onid_imagenChanging(System.Nullable<int> value);
    partial void Onid_imagenChanged();
    #endregion
		
		public usuario()
		{
			this._evento = new EntitySet<evento>(new Action<evento>(this.attach_evento), new Action<evento>(this.detach_evento));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rut", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string rut
		{
			get
			{
				return this._rut;
			}
			set
			{
				if ((this._rut != value))
				{
					this.OnrutChanging(value);
					this.SendPropertyChanging();
					this._rut = value;
					this.SendPropertyChanged("rut");
					this.OnrutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="usuario", Storage="_usuario1", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string usuario1
		{
			get
			{
				return this._usuario1;
			}
			set
			{
				if ((this._usuario1 != value))
				{
					this.Onusuario1Changing(value);
					this.SendPropertyChanging();
					this._usuario1 = value;
					this.SendPropertyChanged("usuario1");
					this.Onusuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="Date NOT NULL")]
		public System.DateTime fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int NOT NULL")]
		public int telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(55) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(1) NOT NULL")]
		public char sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_perfil", DbType="VarChar(5000)")]
		public string descripcion_perfil
		{
			get
			{
				return this._descripcion_perfil;
			}
			set
			{
				if ((this._descripcion_perfil != value))
				{
					this.Ondescripcion_perfilChanging(value);
					this.SendPropertyChanging();
					this._descripcion_perfil = value;
					this.SendPropertyChanged("descripcion_perfil");
					this.Ondescripcion_perfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_imagen", DbType="Int")]
		public System.Nullable<int> id_imagen
		{
			get
			{
				return this._id_imagen;
			}
			set
			{
				if ((this._id_imagen != value))
				{
					this.Onid_imagenChanging(value);
					this.SendPropertyChanging();
					this._id_imagen = value;
					this.SendPropertyChanged("id_imagen");
					this.Onid_imagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_evento", Storage="_evento", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<evento> evento
		{
			get
			{
				return this._evento;
			}
			set
			{
				this._evento.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_evento(evento entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_evento(evento entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.evento")]
	public partial class evento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_evento;
		
		private string _nombre_evento;
		
		private int _id_usuario;
		
		private System.Data.Linq.Binary _fecha_evento;
		
		private string _direccion_evento;
		
		private System.Nullable<int> _edad_minima;
		
		private System.Nullable<int> _edad_maxima;
		
		private int _id_categ;
		
		private int _id_privac;
		
		private string _descrip_evento;
		
		private EntityRef<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_eventoChanging(int value);
    partial void Onid_eventoChanged();
    partial void Onnombre_eventoChanging(string value);
    partial void Onnombre_eventoChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onfecha_eventoChanging(System.Data.Linq.Binary value);
    partial void Onfecha_eventoChanged();
    partial void Ondireccion_eventoChanging(string value);
    partial void Ondireccion_eventoChanged();
    partial void Onedad_minimaChanging(System.Nullable<int> value);
    partial void Onedad_minimaChanged();
    partial void Onedad_maximaChanging(System.Nullable<int> value);
    partial void Onedad_maximaChanged();
    partial void Onid_categChanging(int value);
    partial void Onid_categChanged();
    partial void Onid_privacChanging(int value);
    partial void Onid_privacChanged();
    partial void Ondescrip_eventoChanging(string value);
    partial void Ondescrip_eventoChanged();
    #endregion
		
		public evento()
		{
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_evento", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int id_evento
		{
			get
			{
				return this._id_evento;
			}
			set
			{
				if ((this._id_evento != value))
				{
					this.Onid_eventoChanging(value);
					this.SendPropertyChanging();
					this._id_evento = value;
					this.SendPropertyChanged("id_evento");
					this.Onid_eventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_evento", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string nombre_evento
		{
			get
			{
				return this._nombre_evento;
			}
			set
			{
				if ((this._nombre_evento != value))
				{
					this.Onnombre_eventoChanging(value);
					this.SendPropertyChanging();
					this._nombre_evento = value;
					this.SendPropertyChanged("nombre_evento");
					this.Onnombre_eventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_evento", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary fecha_evento
		{
			get
			{
				return this._fecha_evento;
			}
			set
			{
				if ((this._fecha_evento != value))
				{
					this.Onfecha_eventoChanging(value);
					this.SendPropertyChanging();
					this._fecha_evento = value;
					this.SendPropertyChanged("fecha_evento");
					this.Onfecha_eventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_evento", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string direccion_evento
		{
			get
			{
				return this._direccion_evento;
			}
			set
			{
				if ((this._direccion_evento != value))
				{
					this.Ondireccion_eventoChanging(value);
					this.SendPropertyChanging();
					this._direccion_evento = value;
					this.SendPropertyChanged("direccion_evento");
					this.Ondireccion_eventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad_minima", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> edad_minima
		{
			get
			{
				return this._edad_minima;
			}
			set
			{
				if ((this._edad_minima != value))
				{
					this.Onedad_minimaChanging(value);
					this.SendPropertyChanging();
					this._edad_minima = value;
					this.SendPropertyChanged("edad_minima");
					this.Onedad_minimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad_maxima", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> edad_maxima
		{
			get
			{
				return this._edad_maxima;
			}
			set
			{
				if ((this._edad_maxima != value))
				{
					this.Onedad_maximaChanging(value);
					this.SendPropertyChanging();
					this._edad_maxima = value;
					this.SendPropertyChanged("edad_maxima");
					this.Onedad_maximaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categ", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int id_categ
		{
			get
			{
				return this._id_categ;
			}
			set
			{
				if ((this._id_categ != value))
				{
					this.Onid_categChanging(value);
					this.SendPropertyChanging();
					this._id_categ = value;
					this.SendPropertyChanged("id_categ");
					this.Onid_categChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_privac", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int id_privac
		{
			get
			{
				return this._id_privac;
			}
			set
			{
				if ((this._id_privac != value))
				{
					this.Onid_privacChanging(value);
					this.SendPropertyChanging();
					this._id_privac = value;
					this.SendPropertyChanged("id_privac");
					this.Onid_privacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrip_evento", DbType="VarChar(5000)", UpdateCheck=UpdateCheck.Never)]
		public string descrip_evento
		{
			get
			{
				return this._descrip_evento;
			}
			set
			{
				if ((this._descrip_evento != value))
				{
					this.Ondescrip_eventoChanging(value);
					this.SendPropertyChanging();
					this._descrip_evento = value;
					this.SendPropertyChanged("descrip_evento");
					this.Ondescrip_eventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_evento", Storage="_usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.evento.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.evento.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(int);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
